### ISSUE TITLE
Priority support for queues

### ISSUE THREAD

**Issue by ext-mki** [JohnEstropia/GCDKit#10]
Hi,

can you add support for priorities?
At the moment I've to do this:

`dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0)`

to get a low priority queue.

With GCDKit in use:

`GCDQueue.Custom(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0)).async {}`

but it should be like this:

`GCDQueue.GlobalWithPriority(.LowPrority).async {}`

**Comment by JohnEstropia** [comment]
@ext-mki The `DISPATCH_QUEUE_PRIORITY_LOW` equivalent is `QOS_CLASS_UTILITY`, which you can use in GCDKit with 

```
GCDQueue.Utility.async {
}
```

I suggest you familiarize with Quality-Of-Service classes and the corresponding Priorities that they replaced starting iOS 8:
https://developer.apple.com/library/ios/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html#//apple_ref/doc/uid/TP40015243-CH39-SW42
