### ISSUE TITLE
ITMS-90362 error when using the library and uploading to itunesconnect

### ISSUE THREAD

**Issue by demonar** [JohnEstropia/GCDKit#11]
The project needs to be updated to have a minimum ios version of 8.0
As a reference, the same issue appeared on Alamofire, here's the link: https://github.com/Alamofire/Alamofire/issues/352
attached is the error from the binary upload

In the meantime i'll create a fork and update the settings on it.

Using 1.2.2 version of the lib.

As i see you have 2 targets on the library, but they build the same framework, overwriting the right one, i'll remove the ios7 target on my fork and build it.

![screen shot 2016-04-30 at 14 13 15](https://cloud.githubusercontent.com/assets/1742284/14937445/bf2179e0-0edd-11e6-828c-d1dc702676a2.png)

**Comment by JohnEstropia** [comment]
You cannot use Swift frameworks if your app supports iOS 7. This means you cannot use Cocoapods to manage GCDKit. Use Carthage or git submodule to download GCDKit (or just clone it independently), then include only the .swift files in your project. Don't link GCDKit's xcproj.

**Comment by demonar** [comment]
@JohnEstropia i'm using carthage, the problem is that you have 2 schemes, one for ios 8 and another for ios 7, if i use carthage and do an update with the latest versions of GCDKit and CoreStore, when carthage runs, it's building both schemes, overwriting the ios8 version with the ios7, please check that so you don't have issues with people updating the library as i did :D

**Comment by JohnEstropia** [comment]
@demonar Sorry, I understand the problem now. So your project's minimum version is iOS 8.0, correct?

Should be a bug in Carthage's part, but for a workaround I renamed the output frameworks for the following schemes.
- GCDKit 1.2.4
  - scheme=`GCDKit iOS7` (iOS 7 above): **GCDKit_iOS7.framework** (framework should not be used)
  - scheme=`GCDKit iOS` (iOS 8 above): **GCDKit.framework**
- CoreStore 1.6.4
  - scheme=`CoreStore iOS7` (iOS 7 above): **CoreStore_iOS7.framework** (framework should not be used)
  - scheme=`CoreStore iOS` (iOS 8 above): **CoreStore.framework**

**Comment by demonar** [comment]
Awesome, thanks for the quick response :D
