### ISSUE TITLE
OS X support?

### ISSUE THREAD

**Issue by h1994st** [JohnEstropia/GCDKit#4]
Hi John, 

GCDKit is a good library when using swift. I'm just wondering whether it supports osx platform, since the framework that GCDKit needs is `Foundation` only.

**Comment by JohnEstropia** [comment]
Thanks for the feedback! I don't have much experience with OS X development so I'd appreciate if you have pointers on some behavior differences or things to watch out for. I'll take a look at the OS X API for Grand Central Dispatch and see how far GCDKit can support.

**Comment by JohnEstropia** [comment]
@h1994st Sorry for the long wait. I pushed OSX and watchOS targets to the develop branch. I'll add it to the Cocoapods repository later in the day
