### ISSUE TITLE
Can't build with xcode 6.4

### ISSUE THREAD

**Issue by jarleif** [JohnEstropia/GCDKit#5]
Hi I am trying to use your latest Pod (GCDKit 1.1.1) but I can't get it to build with Xcode Version 6.4 (6E35b) for iOS 8. I get 63 issues and they seem to be based around @available(iOS, introduced=7.0) Any help would be great.

**Comment by jarleif** [comment]
I also tried downloading the files straight from here and opened the downloaded project, but I got the same issue.

**Comment by jarleif** [comment]
Seems it needs Xcode 7. An older version is working.

**Comment by JohnEstropia** [comment]
@jarleif, apologies for not being able to reply sooner.

For Swift 1.2 you'll need to use the release tagged [1.0.1](https://github.com/JohnEstropia/GCDKit/releases/tag/1.0.1). Hope you got it working!

I'll update the readme to reflect this. Thanks for the feedback!
