### ISSUE TITLE
EXC_BAD_INSTRUCTION on dispatch_block_notify

### ISSUE THREAD

**Issue by ekampf** [JohnEstropia/GCDKit#6]
Im getting an EXC_BAD_INSTRUCTION on GCDBlock.notify when in calls dispatch_block_notify.
The calling cod looks like this:

```
GCDBlock.async(.Default) {
            ... does she work ...
        }.notify(.Main) {

        }
```

Any idea?
(Im using Xcode 7.0.1)

**Comment by JohnEstropia** [comment]
@ekampf Thanks for the feedback!
Unfortunately, this was a known bug in Swift 2.0 where dispatch_block API is unusable in swift: https://forums.developer.apple.com/message/50922#50922

They have fixed this in Swift 2.1 (XCode 7.1 beta), but there is currently no workaround with swift code.
For now you can just avoid chaining and write it like this:

``` swift
GCDBlock.async(.Default) {
    // ...
    GCDBlock.async(.Main) {
        // ...
    }
}
```

**Comment by ekampf** [comment]
Thanks!

**Comment by JohnEstropia** [comment]
Just a heads up, XCode 7.1 was released in the Mac AppStore today which fixes this bug. GCDKit unit tests now work as they did before :+1:

**Comment by ekampf** [comment]
:+1:
